### PR TITLE
Add Async Interface with FireStore for projects

### LINKED ISSUE #7: Defining an API, to interact with FireBase (send / request data)

### PR DESCRIPTION
**Pull request by PaulCoral**
An Interace with FireBase FireStore to add and get projects from it.

### CODE REVIEW

**Comment by PaulCoral** [comment]
The base code is present 
Unit tests are needed

**Comment by PaulCoral** [comment]
1. the codeclimate style issues are false positive, thus should be ignored
2. As said on the course forum, test coverage, on code that relies strongly on external dependency, cannot be achieved

**Review by arnauds5 — APPROVED** [review]
Looks good

**Review by asfoury — APPROVED** [review]
Looks good.

**Pull request merged**
